import { Shrikhand, Prompt } from "next/font/google";
import "./globals.css";

import Nav from "/components/Nav/Nav.jsx";
import Footer from "/components/Footer/Footer.jsx";

const font1 = Shrikhand({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-shrikhand",
});
const font2 = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-prompt",
});

export const metadata = {
  title: "Annamaria's Portfolio",
  description: "Generated by create next app",
  icons: [
    {
      icon: "/favicon.ico",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font1.className} ${font2.className}`}>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
