import { Shrikhand, Prompt } from "next/font/google";
import "./globals.css";

import Nav from "/components/Nav/Nav.jsx";

const font1 = Shrikhand({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-shrikhand",
});
const font2 = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-prompt",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font1.className} ${font2.className}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
